package com.cuber.devfest.data.source.remote.exception

class ApiErrorCode {

    companion object {
        val SUCCESS = "0"
        val ERROR = "9999"
    }

}